// Major Indian job-hub cities + Remote, for the Location dropdown.
export const INDIAN_CITIES = [
  "Remote",
  "Bengaluru",
  "Mumbai",
  "Delhi",
  "Gurugram",
  "Noida",
  "Pune",
  "Hyderabad",
  "Chennai",
  "Kolkata",
  "Ahmedabad",
  "Jaipur",
  "Chandigarh",
  "Indore",
  "Kochi",
  "Coimbatore",
  "Lucknow",
  "Nagpur",
  "Bhubaneswar",
  "Visakhapatnam",
  "Surat",
  "Other",
];
